# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[(b'MASCULINE', b'masculine'), (b'FEMININE', b'feminine'), (b'NEUTER', b'neuter')], max_length=8)),
                ('lexical_category', models.CharField(choices=[(b'NOUN', b'noun'), (b'ADJECTIVE', b'adjective')], max_length=9)),
                ('regular', models.BooleanField(default=True)),
                ('nominative_singular', models.CharField(max_length=100)),
                ('accusative_singular', models.CharField(max_length=100)),
                ('dative_singular', models.CharField(max_length=100)),
                ('genitive_singular', models.CharField(max_length=100)),
                ('prepositional_singular', models.CharField(max_length=100)),
                ('instrumental_singular', models.CharField(max_length=100)),
                ('nominative_plural', models.CharField(max_length=100)),
                ('accusative_plural', models.CharField(max_length=100)),
                ('dative_plural', models.CharField(max_length=100)),
                ('genitive_plural', models.CharField(max_length=100)),
                ('prepositional_plural', models.CharField(max_length=100)),
                ('instrumental_plural', models.CharField(max_length=100)),
            ],
        ),
    ]
